### ISSUE TITLE
Master Branch "sudo wtemulator" Not Ends UP with CLI Interface

### ISSUE THREAD

**Issue by haiyunhzhang** [Melacon/WirelessTransportEmulator#5]
I followed the steps listed by https://github.com/Melacon/WirelessTransportEmulator to install the simulator container. Everhting went on with no problems, except when running from base folder,

sudo wtemulator --config=config.json --topo=topology.json --xml=yang/microwave-model-config.xml

Error was caught in debug.log.

[2018.05.21-16:25:39] - [DEBUG] interface.py:775 - Found ltp with ltp=eth4
[2018.05.21-16:25:39] - [DEBUG] networkelement.py:542 - Created docker container Simulator-1 having IP=192.168.254.250
[2018.05.21-16:25:41] - [CRITICAL] emulator.py:197 - Failed executing command docker start Simulator-1
[2018.05.21-16:25:41] - [CRITICAL] emulator.py:199 - Stderr: Error response from daemon: driver failed programming external connectivity on endpoint Simulator-1 (8403e3531146f434f8672c6e937aca67a3979d98f9813df26c2dd54a546278f7): Error starting userland proxy: listen tcp 192.168.254.250:15001: bind: cannot assign requested address
[2018.05.21-16:25:41] - [DEBUG] wtemulator:146 - Traceback (most recent call last):
  File "/usr/local/bin/wtemulator", line 130, in <module>
    EmulatorRunner()
  File "/usr/local/bin/wtemulator", line 30, in __init__
    self.begin()
  File "/usr/local/bin/wtemulator", line 114, in begin
    e.startEmulator()
  File "/usr/local/lib/python3.6/dist-packages/wireless_emulator/emulator.py", line 180, in startEmulator
    self.createNetworkElements()
  File "/usr/local/lib/python3.6/dist-packages/wireless_emulator/emulator.py", line 136, in createNetworkElements
    neObj.addNetworkElement()
  File "/usr/local/lib/python3.6/dist-packages/wireless_emulator/networkelement.py", line 621, in addNetworkElement
    self.startDockerContainer()
  File "/usr/local/lib/python3.6/dist-packages/wireless_emulator/networkelement.py", line 583, in startDockerContainer
    self.emEnv.executeCommandInOS(stringCmd)
  File "/usr/local/lib/python3.6/dist-packages/wireless_emulator/emulator.py", line 200, in executeCommandInOS
    raise RuntimeError
RuntimeError

[2018.05.21-16:25:41] - [CRITICAL] clean.py:99 - Could not kill docker container Simulator-1
 Stderr: Error response from daemon: Cannot kill container: Simulator-1: Container d25a85b7b4cf17841ee41fb2b934ae89892e74c9570b9d3638d7c92252192a7d is not running

May I ask whether I need to do anything from the network configuration side to fix the problem? Sorry that I am new to the simulator and I just followed the instructions and do not know how to debug the issue.

Regards,

Harry
[debug.log](https://github.com/Melacon/WirelessTransportEmulator/files/2023914/debug.log)

**Comment by haiyunhzhang** [comment]
I think this is a network configuration issue.
